export const LOAD_MOVIES = '@@APP/ROOT/LOAD_MOVIES';
export const FAVORITE_ADD = '@@APP/ROOT/FAVORITE_ADD';
export const MOVIE_SEARCH = '@@APP/ROOT/MOVIE_SEARCH';
export const FILTER_FAVORITE = '@@APP/ROOT/FILTER_FAVORITE';
export const RESET_ALL = '@@APP/ROOT/RESET_ALL';
